# Configuration for Jekyll/GitHub Pages demo
# This demonstrates generating Jekyll-compatible YAML data files

bibtex:
  bib_dir: "../../data/bib"
  files:
    - name: "siddpubs-journal.bib"
      category: "Journal Papers"
    - name: "siddpubs-conf.bib"
      category: "Conference Papers"
    - name: "siddpubs-misc.bib"
      category: "Other Papers"

projects:
  config_file: "../../data/projects-config.yaml"

output:
  pdf_base_url: "https://personalrobotics.cs.washington.edu/publications/"

