# Configuration for Jekyll/GitHub Pages demo
# This demonstrates generating Jekyll-compatible YAML data files

bibtex:
  source_url: "https://raw.githubusercontent.com/personalrobotics/pubs/refs/heads/siddhss5-href-flip-bug"
  # For Jekyll, store BibTeX in the Jekyll site's _data directory
  cache_dir: "~/code/siddhss5.github.io/_data/bib"
  files:
    - name: "siddpubs-journal.bib"
      category: "Journal Papers"
    - name: "siddpubs-conf.bib"
      category: "Conference Papers"
    - name: "siddpubs-misc.bib"
      category: "Other Papers"

projects:
  # For Jekyll, projects config lives in the Jekyll site
  config_file: "~/code/siddhss5.github.io/_data/projects_config.yaml"

output:
  pdf_base_url: "https://personalrobotics.cs.washington.edu/publications/"

