# Configuration for standalone HTML generator demo
# This demonstrates generating static HTML pages with prl_bib2html

bibtex:
  source_url: "https://raw.githubusercontent.com/personalrobotics/pubs/master"
  cache_dir: "../../data/bib"
  files:
    - name: "siddpubs-journal.bib"
      category: "Journal Papers"
    - name: "siddpubs-conf.bib"
      category: "Conference Papers"
    - name: "siddpubs-misc.bib"
      category: "Other Papers"

projects:
  config_file: "../../data/projects.yaml"

output:
  pdf_base_url: "https://personalrobotics.cs.washington.edu/publications/"

